package com.tugoapp.mobile.utils

object AppConstant {
    val RC_SIGN_IN: Int = 9001
    const val SPLASH_TIME: Long = 3000
    const val TIMESTAMP_FORMAT = "yyyy-MM-dd HH:mm:ss"
    const val FIREBASE_VERIFICATION_ID = "FIREBASE_VERIFICATION_ID"
    const val FIREBASE_RESEND_TOKEN = "FIREBASE_RESEND_TOKEN"
    const val FIREBASE_PHONE_NUMBER = "FIREBASE_PHONE_NUMBER"
    const val FIREBASE_EMAIL_ADDRESS = "FIREBASE_EMAIL_ADDRESS"
    const val SELECTED_PROVIDER_FOR_PROVIDER_DETAIL = "SELECTED_PROVIDER_FOR_PROVIDER_DETAIL"
    const val SELECTED_CATEGORY_FOR_PROVIDERS = "SELECTED_CATEGORY_FOR_PROVIDERS"
    const val ALL_CATEGORY_FOR_PROVIDERS = "ALL_CATEGORY_FOR_PROVIDERS"
}