package com.tugoapp.mobile.utils

object AppConstant {

    const val WALKTHROUGH_PREFS_NAME = "Walkthrough_Pref_File"
    const val FIREBASE_SENDER_ID = "908606240987"

    val RC_SIGN_IN: Int = 9001
    const val SPLASH_TIME: Long = 2800
    const val TIMESTAMP_FORMAT = "yyyy-MM-dd HH:mm:ss"
    const val FIREBASE_VERIFICATION_ID = "FIREBASE_VERIFICATION_ID"
    const val FIREBASE_RESEND_TOKEN = "FIREBASE_RESEND_TOKEN"
    const val FIREBASE_PHONE_NUMBER = "FIREBASE_PHONE_NUMBER"
    const val FIREBASE_EMAIL_ADDRESS = "FIREBASE_EMAIL_ADDRESS"
    const val SELECTED_PROVIDER_FOR_PROVIDER_DETAIL = "SELECTED_PROVIDER_FOR_PROVIDER_DETAIL"
    const val SELECTED_CATEGORY_FOR_PROVIDERS = "SELECTED_CATEGORY_FOR_PROVIDERS"
    const val ALL_CATEGORY_FOR_PROVIDERS = "ALL_CATEGORY_FOR_PROVIDERS"
    const val SAMPLE_MENU_DATA = "SAMPLE_MENU_DATA"
    const val SELECTED_PLAN_OBJECT = "SELECTED_PLAN_OBJECT"
    const val SELECTED_MEAL_PLAN = "SELECTED_MEAL_PLAN"
    const val SELECTED_MEAL_PLAN_TRIAL = "SELECTED_MEAL_PLAN_TRIAL"
    const val ADDRESS_TO_EDIT = "ADDRESS_TO_EDIT"
    const val SELECTED_ORDER_FOR_DETAIL = "SELECTED_ORDER_FOR_DETAIL"
    const val SELECTED_ORDER_IS_HISTORY = "SELECTED_ORDER_IS_HISTORY"
    const val START_DATE_FOR_THANKYOU = "START_DATE_FOR_THANKYOU"
    const val IS_FROM_DELIVERY_SCREEN = "IS_FROM_DELIVERY_SCREEN"
    const val ORDER_DETAIL_ORDER_ID = "ORDER_DETAIL_ORDER_ID"
    const val BUSINESS_ID = "BUSINESS_ID"
    const val FULL_NAME = "FULL_NAME"
    const val USER_DETAIL_DATA = "USER_DETAIL_DATA"
    const val SAMPLE_MENU_COMPANYLOGO = "SAMPLE_MENU_COMPANYLOGO"
    const val IS_FROM_EDIT_PROFILE = "IS_FROM_EDIT_PROFILE"
    const val IS_FROM_TERMS_COND = "IS_FROM_TERMS_COND"
    const val PAYMENT_CONFIG_INFO = "PAYMENT_CONFIG_INFO"
    const val PREF_KEY_SELECTED_LOCATION = "PREF_KEY_SELECTED_LOCATION"
    const val PREF_KEY_PUSH_TOKEN = "PREF_KEY_PUSH_TOKEN"

    const val IS_LOGGED_IN = "IS_LOGGED_IN"
    const val LOGGED_IN_EMAIL = "LOGGED_IN_EMAIL"
    const val LOGGED_IN_PHONE = "LOGGED_IN_PHONE"
    const val PREF_KEY_SHOW_DATE_DIALOG = "PREF_KEY_SHOW_DATE_DIALOG"
}